### ISSUE TITLE
Cmake fails to run

### ISSUE THREAD

**Issue by eladshabo** [IntelRealSense/realsense_sdk#19]
When trying to run cmake after creating new folder named "build" I get this error:
![cmake error](https://cloud.githubusercontent.com/assets/12895772/21529696/fc7edede-cd43-11e6-8b79-51e71e46c72d.jpg)

Eventually, I succeeded running cmake with this w/a:
1. Create folder outside of the sdk folder (“sdk_build” in this case)
2. Run command: B/home/ntuser/sdk_build -H../Downloads/realsense_sdk/
3. Continue installation normally for “sdk_build” folder (make –j && sudo make install)

**Comment by EldarZ** [comment]
Hi @eladshabo, This message appears when the user tries to generate cmake output under the sdk src directory, it supposed to prevent you from cluttering the sources directory from any cmake generated outputs.
I'm guessing you ran cmake first under the source dir and due to cached cmake files this message kept appearing. Assuming this was your issue, clearing cmake cached outputs from the src directory manually, or by using git to reset or by cloning the sdk to a clean directory was possibly what solved your issue. Can you confirm?
